apiVersion: apps/v1
kind: Deployment
metadata:
  name: r2-alpine-deploy
  labels:
    app: r2-alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: r2-alpine
  template:
    metadata:
      labels:
        app: r2-alpine
    spec:
      nodeSelector:
        role: R2
      containers:
      - name: r2-alpine
        image: alpine
        command: ['sh', '-c', 'apk add bind-tools iperf3 curl bash tcpdump && sleep 36000']
      restartPolicy: Always

