apiVersion: apps/v1
kind: Deployment
metadata:
  name: r2-service-deploy
  labels:
    app: r2-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: r2-svc
  template:
    metadata:
      labels:
        app: r2-svc
    spec:
      nodeSelector:
        role: R2
      containers:
      - name: webapp
        image: dannypsnl/webapp
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: r2-webapp-service
spec:
  selector:
    app: r2-svc
  ports:
  - port: 80
    targetPort: 8080
