apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: debug
  namespace: debug
  labels:
    app: debug
spec:
  selector:
    matchLabels:
      app: debug
  template:
    metadata:
      labels:
        app: debug
    spec:
      hostNetwork: true
      containers:
      - name: debug
        image: dannypsnl/debug
        command: ['sh', '-c', 'sleep 360000000']
      restartPolicy: Always
