apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-deploy
  labels:
    app: golang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang
  template:
    metadata:
      labels:
        app: golang
    spec:
      containers:
      - name: golang
        image: golang:1.11-alpine3.8
        command: ['sh', '-c', 'apk add bind-tools iperf3 curl bash && sleep 36000']
      restartPolicy: Always

